<h1>Login</h1>

<?php if($messageError): ?>
    <div class="alert alert-danger alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
        <strong>Erro!</strong> <?= $messageError; ?>
    </div>
<?php endif; ?>
<?php

$username = $form->get('username');
$username->setAttribute('class', 'form-control');
$username->setLabelAttributes(['class' => 'control-label']);

$password = $form->get('password');
$password->setAttribute('class', 'form-control');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('login'));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?=$this->formLabel($username);?>
    <?=$this->formElement($username);?>
    <?=$this->formElementErrors($username, ['class' => 'help-block']);?>
</div>


<div class="form-group">
    <?=$this->formLabel($password);?>
    <?=$this->formElement($password);?>
    <?=$this->formElementErrors($password, ['class' => 'help-block']);?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();
?>