<h1>Add new Post</h1>

<?php

$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setLabelAttributes(['class' => 'control-label']);

$content = $form->get('content');
$content->setAttribute('class', 'form-control');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('post', ['action'=>'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group is-invalid">
    <?=$this->formLabel($title);?>
    <?=$this->formElement($title);?>
    <?=$this->formElementErrors($title, ['class' => 'help-block']);?>
</div>


<div class="form-group">
    <?=$this->formLabel($content);?>
    <?=$this->formElement($content);?>
    <?=$this->formElementErrors($content, ['class' => 'help-block']);?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>